### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by code101015** [Chave0v0/YONYOU-TOOL#1]
java -jar YONYOU-TOOL-2.0.6.jar
错误: 找不到或无法加载主类 com.chave.main.Main
原因: java.lang.NoClassDefFoundError: javafx/application/Application

**Comment by Chave0v0** [comment]
什么版本的java环境

**Comment by Chave0v0** [comment]
什么版本的java环境  这边用java8运行正常

**Comment by Chave0v0** [comment]
建议java8  高版本需要手动添加javafx
